-- MGEN CRM V7 setup
-- Run this once in Supabase SQL Editor.
-- This does NOT delete your existing leads.

create table if not exists public.lead_files (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  lead_id bigint references public.leads(id) on delete cascade,
  file_name text not null,
  file_type text not null,
  file_path text not null
);

alter table public.lead_files enable row level security;

drop policy if exists "Allow public read lead files" on public.lead_files;
drop policy if exists "Allow public insert lead files" on public.lead_files;

create policy "Allow public read lead files"
on public.lead_files
for select
to anon
using (true);

create policy "Allow public insert lead files"
on public.lead_files
for insert
to anon
with check (true);

create table if not exists public.proposals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  lead_id bigint references public.leads(id) on delete cascade,
  title text not null,
  system_size_kw numeric default 0,
  panel_count numeric default 0,
  battery_kwh numeric default 0,
  annual_generation numeric default 0,
  annual_saving numeric default 0,
  payback_years text,
  proposal_status text default 'Draft'
);

alter table public.proposals enable row level security;

drop policy if exists "Allow public read proposals" on public.proposals;
drop policy if exists "Allow public insert proposals" on public.proposals;

create policy "Allow public read proposals"
on public.proposals
for select
to anon
using (true);

create policy "Allow public insert proposals"
on public.proposals
for insert
to anon
with check (true);

create table if not exists public.customer_journey (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  lead_id bigint references public.leads(id) on delete cascade,
  stage text not null,
  note text
);

alter table public.customer_journey enable row level security;

drop policy if exists "Allow public read customer journey" on public.customer_journey;
drop policy if exists "Allow public insert customer journey" on public.customer_journey;

create policy "Allow public read customer journey"
on public.customer_journey
for select
to anon
using (true);

create policy "Allow public insert customer journey"
on public.customer_journey
for insert
to anon
with check (true);
