-- MGEN CRM V6 file upload setup

-- 1) Create metadata table for files attached to leads
create table if not exists public.lead_files (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  lead_id bigint references public.leads(id) on delete cascade,
  file_name text not null,
  file_type text not null,
  file_path text not null
);

alter table public.lead_files enable row level security;

drop policy if exists "Allow public read lead files" on public.lead_files;
drop policy if exists "Allow public insert lead files" on public.lead_files;

create policy "Allow public read lead files"
on public.lead_files
for select
to anon
using (true);

create policy "Allow public insert lead files"
on public.lead_files
for insert
to anon
with check (true);

-- 2) In Supabase Storage, create a PUBLIC bucket manually named:
-- lead-files
--
-- Then add storage policies if needed:
-- Storage > Policies > lead-files
-- Allow anon select and insert during prototype stage.
