create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text not null,
  address text,
  postcode text,
  phone text,
  email text,
  monthly_bill numeric default 0,
  annual_usage numeric default 0,
  roof_type text,
  stage text default 'New Lead',
  notes text
);

alter table public.leads enable row level security;

drop policy if exists "Allow public insert leads" on public.leads;
drop policy if exists "Allow public read leads" on public.leads;

create policy "Allow public insert leads"
on public.leads
for insert
to anon
with check (true);

create policy "Allow public read leads"
on public.leads
for select
to anon
using (true);
